# Generated by Django 5.0.3 on 2024-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarvanVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('carName', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
