# Generated by Django 5.0.3 on 2024-04-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvanvehicle',
            name='car_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carvanvehicle',
            name='owner_first_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carvanvehicle',
            name='owner_last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carvanvehicle',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
