# Generated by Django 5.0.3 on 2024-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0002_carvanvehicle_car_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.FileField(upload_to='media')),
                ('driving_licence', models.FileField(upload_to='media')),
                ('puc', models.FileField(upload_to='media')),
                ('car_insurence', models.FileField(upload_to='media')),
            ],
        ),
    ]
