# Generated by Django 5.0.3 on 2024-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0008_alter_carvanvehicle_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdocument',
            name='owner_first_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostdocument',
            name='owner_last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carvanvehicle',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='car_insurence',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='driving_licence',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='identity',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='puc',
            field=models.FileField(upload_to='images'),
        ),
    ]
