# Generated by Django 5.0.3 on 2024-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0009_hostdocument_owner_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_first_name', models.CharField(max_length=50)),
                ('owner_last_name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('carName', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('car_number', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('identity', models.FileField(upload_to='images')),
                ('driving_licence', models.FileField(upload_to='images')),
                ('puc', models.FileField(upload_to='images')),
                ('car_insurence', models.FileField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='CarvanVehicle',
        ),
        migrations.DeleteModel(
            name='HostDocument',
        ),
    ]
