# Generated by Django 5.0.3 on 2024-04-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0013_rename_car_number_hostdetails_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdocument',
            name='car_insurence',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='driving_licence',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='identity',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='puc',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='registration_card',
            field=models.FileField(upload_to=''),
        ),
    ]
