# Generated by Django 5.0.3 on 2024-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0015_alter_hostdocument_car_insurence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdocument',
            name='identity',
            field=models.FileField(upload_to=''),
        ),
    ]
