# Generated by Django 5.0.3 on 2024-04-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0018_alter_hostdocument_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdocument',
            name='identity',
            field=models.FileField(upload_to='gurjar'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='registration_card',
            field=models.FileField(upload_to='sagar'),
        ),
    ]
