# Generated by Django 5.0.3 on 2024-04-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0019_alter_hostdocument_identity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='car/carImage')),
                ('carName', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hostdetails',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='hostdetails',
            name='carName',
        ),
        migrations.RemoveField(
            model_name='hostdetails',
            name='price',
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='identity',
            field=models.FileField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='registration_card',
            field=models.FileField(upload_to='image'),
        ),
    ]
