# Generated by Django 5.0.3 on 2024-04-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0020_addcar_remove_hostdetails_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='email_address',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
