# Generated by Django 5.0.3 on 2024-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0021_hostdetails_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcar',
            name='Milage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='Transmission',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='fuel',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='seat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
