# Generated by Django 5.0.3 on 2024-04-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0022_addcar_milage_addcar_transmission_addcar_fuel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcar',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='addcar',
            name='Milage',
        ),
        migrations.RemoveField(
            model_name='addcar',
            name='Transmission',
        ),
        migrations.RemoveField(
            model_name='addcar',
            name='fuel',
        ),
        migrations.AddField(
            model_name='addcar',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='transmission_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addcar',
            name='carName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addcar',
            name='img',
            field=models.ImageField(upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='addcar',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='addcar',
            name='brand',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
