# Generated by Django 5.0.3 on 2024-04-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0023_remove_addcar_brand_remove_addcar_milage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='img',
            field=models.ImageField(upload_to='car/main_Photo'),
        ),
    ]
