# Generated by Django 5.0.3 on 2024-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0024_alter_addcar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdocument',
            name='car_insurence',
            field=models.FileField(upload_to='Host_Document'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='driving_licence',
            field=models.FileField(upload_to='Host_Document'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='identity',
            field=models.FileField(upload_to='Host_Document'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='puc',
            field=models.FileField(upload_to='Host_Document'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='registration_card',
            field=models.FileField(upload_to='Host_Document'),
        ),
    ]
