# Generated by Django 5.0.3 on 2024-04-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0025_alter_hostdocument_car_insurence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostdocument',
            name='car_insurence',
        ),
        migrations.RemoveField(
            model_name='hostdocument',
            name='driving_licence',
        ),
        migrations.RemoveField(
            model_name='hostdocument',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='hostdocument',
            name='puc',
        ),
        migrations.AddField(
            model_name='hostdocument',
            name='adhar_card',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostdocument',
            name='car_insurance',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostdocument',
            name='driving_license',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostdocument',
            name='puc_card',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='registration_card',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
