# Generated by Django 5.0.3 on 2024-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0027_alter_hostdocument_adhar_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcar',
            old_name='img',
            new_name='front_img',
        ),
        migrations.AddField(
            model_name='addcar',
            name='Back_seat',
            field=models.ImageField(default=0, upload_to='car/Back_seat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='Dashboard_img',
            field=models.ImageField(default=0, upload_to='car/Dashboard_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='Inside_img',
            field=models.ImageField(default=0, upload_to='car/Inside_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcar',
            name='back_img',
            field=models.ImageField(default=0, upload_to='car/back_img'),
            preserve_default=False,
        ),
    ]
