# Generated by Django 5.0.3 on 2024-05-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0028_rename_img_addcar_front_img_addcar_back_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcar',
            name='Back_seat',
        ),
        migrations.RemoveField(
            model_name='addcar',
            name='Dashboard_img',
        ),
        migrations.RemoveField(
            model_name='addcar',
            name='Inside_img',
        ),
        migrations.RemoveField(
            model_name='addcar',
            name='back_img',
        ),
        migrations.RemoveField(
            model_name='addcar',
            name='front_img',
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carvanDriveApp.addcar')),
            ],
        ),
    ]
