# Generated by Django 5.0.3 on 2024-05-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvanDriveApp', '0029_remove_addcar_back_seat_remove_addcar_dashboard_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdocument',
            name='adhar_card',
            field=models.ImageField(upload_to='documents/adhar'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='car_insurance',
            field=models.ImageField(upload_to='documents/Incurance'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='driving_license',
            field=models.ImageField(upload_to='documents/DL'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='puc_card',
            field=models.ImageField(upload_to='documents/PUC'),
        ),
        migrations.AlterField(
            model_name='hostdocument',
            name='registration_card',
            field=models.ImageField(upload_to='documents/RC'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carvanDriveApp.addcar')),
            ],
        ),
    ]
